site_name: Georgia HEAT Roleplay
theme:  
  name: material
  custom_dir: overrides
  features:
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep orange
      accent: amber
  logo: assets/images/logo.png

extra:
  social:
    - icon: fontawesome/brands/tiktok
      link: ""
    - icon: fontawesome/brands/discord
      link: ""

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: false
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.snippets
  - abbr
  - def_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/app.js

copyright: |
  &copy; 2025 <a href="http://spacecoastrp.co" target="_blank" rel="noopener">The Spacecoast Network</a>

nav:
  - Home: index.html
  - Rules:
    - Gameplay Rules: gameplay-rules.md
    - Server Rules: ""
    - Community Rules: ""
  - Penal Code:
    - '[Title 16] Crimes and Offenses': title-16.md
    - '[Title 40] Motor Vehicles and Traffic': title-40.md
  - Bill of Rights: bill-of-rights.md

