site_name: Georgia HEAT Roleplay
theme:  
  name: material
  features:
    - navigation.instant
    - toc.integrate
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tabs
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: deep orange
      accent: amber
  logo: assets/images/logo.png

extra:
  social:
    - icon: fontawesome/brands/tiktok
      link: ""
    - icon: fontawesome/brands/discord
      link: ""

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: false

extra_css:
  - stylesheets/extra.css



copyright: |
  &copy; 2025 <a href="http://spacecoastrp.co" target="_blank" rel="noopener">The Spacecoast Network</a>

nav:
  - Home: index.md
  - Rules:
    - Gameplay Rules: gameplay-ruless.md
    - Server Rules: ""
    - Community Rules: ""
  - Penal Code:
    - National Laws:
      - '[40] Motor Vehicles and Traffic':
        - Moving Violations:
          - 40-6-181 | Speeding: 'penal-code/national-laws/moving-violations/speeding.md'
  - Bill of Rights: bill-of-rights.md

